//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public interface ChatServicePrx extends com.zeroc.Ice.ObjectPrx
{
    default User login(String username)
    {
        return login(username, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default User login(String username, java.util.Map<String, String> context)
    {
        return _iceI_loginAsync(username, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<User> loginAsync(String username)
    {
        return _iceI_loginAsync(username, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<User> loginAsync(String username, java.util.Map<String, String> context)
    {
        return _iceI_loginAsync(username, context, false);
    }

    /**
     * @hidden
     * @param iceP_username -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<User> _iceI_loginAsync(String iceP_username, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<User> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "login", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_username);
                 }, istr -> {
                     User ret;
                     ret = User.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default void logout(String userId)
    {
        logout(userId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void logout(String userId, java.util.Map<String, String> context)
    {
        _iceI_logoutAsync(userId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> logoutAsync(String userId)
    {
        return _iceI_logoutAsync(userId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> logoutAsync(String userId, java.util.Map<String, String> context)
    {
        return _iceI_logoutAsync(userId, context, false);
    }

    /**
     * @hidden
     * @param iceP_userId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_logoutAsync(String iceP_userId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "logout", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_userId);
                 }, null);
        return f;
    }

    default void sendPrivateMessage(String fromUser, String toUser, String message)
        throws UserNotFound
    {
        sendPrivateMessage(fromUser, toUser, message, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void sendPrivateMessage(String fromUser, String toUser, String message, java.util.Map<String, String> context)
        throws UserNotFound
    {
        try
        {
            _iceI_sendPrivateMessageAsync(fromUser, toUser, message, context, true).waitForResponseOrUserEx();
        }
        catch(UserNotFound ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> sendPrivateMessageAsync(String fromUser, String toUser, String message)
    {
        return _iceI_sendPrivateMessageAsync(fromUser, toUser, message, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> sendPrivateMessageAsync(String fromUser, String toUser, String message, java.util.Map<String, String> context)
    {
        return _iceI_sendPrivateMessageAsync(fromUser, toUser, message, context, false);
    }

    /**
     * @hidden
     * @param iceP_fromUser -
     * @param iceP_toUser -
     * @param iceP_message -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sendPrivateMessageAsync(String iceP_fromUser, String iceP_toUser, String iceP_message, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendPrivateMessage", null, sync, _iceE_sendPrivateMessage);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_fromUser);
                     ostr.writeString(iceP_toUser);
                     ostr.writeString(iceP_message);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_sendPrivateMessage =
    {
        UserNotFound.class
    };

    default void sendGroupMessage(String fromUser, String groupName, String message)
        throws GroupNotFound
    {
        sendGroupMessage(fromUser, groupName, message, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void sendGroupMessage(String fromUser, String groupName, String message, java.util.Map<String, String> context)
        throws GroupNotFound
    {
        try
        {
            _iceI_sendGroupMessageAsync(fromUser, groupName, message, context, true).waitForResponseOrUserEx();
        }
        catch(GroupNotFound ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> sendGroupMessageAsync(String fromUser, String groupName, String message)
    {
        return _iceI_sendGroupMessageAsync(fromUser, groupName, message, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> sendGroupMessageAsync(String fromUser, String groupName, String message, java.util.Map<String, String> context)
    {
        return _iceI_sendGroupMessageAsync(fromUser, groupName, message, context, false);
    }

    /**
     * @hidden
     * @param iceP_fromUser -
     * @param iceP_groupName -
     * @param iceP_message -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sendGroupMessageAsync(String iceP_fromUser, String iceP_groupName, String iceP_message, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendGroupMessage", null, sync, _iceE_sendGroupMessage);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_fromUser);
                     ostr.writeString(iceP_groupName);
                     ostr.writeString(iceP_message);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_sendGroupMessage =
    {
        GroupNotFound.class
    };

    default String createGroup(String groupName, String creator)
    {
        return createGroup(groupName, creator, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String createGroup(String groupName, String creator, java.util.Map<String, String> context)
    {
        return _iceI_createGroupAsync(groupName, creator, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> createGroupAsync(String groupName, String creator)
    {
        return _iceI_createGroupAsync(groupName, creator, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> createGroupAsync(String groupName, String creator, java.util.Map<String, String> context)
    {
        return _iceI_createGroupAsync(groupName, creator, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupName -
     * @param iceP_creator -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_createGroupAsync(String iceP_groupName, String iceP_creator, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "createGroup", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_groupName);
                     ostr.writeString(iceP_creator);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default void joinGroup(String groupName, String user)
        throws GroupNotFound
    {
        joinGroup(groupName, user, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void joinGroup(String groupName, String user, java.util.Map<String, String> context)
        throws GroupNotFound
    {
        try
        {
            _iceI_joinGroupAsync(groupName, user, context, true).waitForResponseOrUserEx();
        }
        catch(GroupNotFound ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> joinGroupAsync(String groupName, String user)
    {
        return _iceI_joinGroupAsync(groupName, user, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> joinGroupAsync(String groupName, String user, java.util.Map<String, String> context)
    {
        return _iceI_joinGroupAsync(groupName, user, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupName -
     * @param iceP_user -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_joinGroupAsync(String iceP_groupName, String iceP_user, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "joinGroup", null, sync, _iceE_joinGroup);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_groupName);
                     ostr.writeString(iceP_user);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_joinGroup =
    {
        GroupNotFound.class
    };

    default void leaveGroup(String groupName, String user)
        throws GroupNotFound
    {
        leaveGroup(groupName, user, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void leaveGroup(String groupName, String user, java.util.Map<String, String> context)
        throws GroupNotFound
    {
        try
        {
            _iceI_leaveGroupAsync(groupName, user, context, true).waitForResponseOrUserEx();
        }
        catch(GroupNotFound ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> leaveGroupAsync(String groupName, String user)
    {
        return _iceI_leaveGroupAsync(groupName, user, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> leaveGroupAsync(String groupName, String user, java.util.Map<String, String> context)
    {
        return _iceI_leaveGroupAsync(groupName, user, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupName -
     * @param iceP_user -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_leaveGroupAsync(String iceP_groupName, String iceP_user, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "leaveGroup", null, sync, _iceE_leaveGroup);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_groupName);
                     ostr.writeString(iceP_user);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_leaveGroup =
    {
        GroupNotFound.class
    };

    default Group getGroupDetails(String groupName)
        throws GroupNotFound
    {
        return getGroupDetails(groupName, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Group getGroupDetails(String groupName, java.util.Map<String, String> context)
        throws GroupNotFound
    {
        try
        {
            return _iceI_getGroupDetailsAsync(groupName, context, true).waitForResponseOrUserEx();
        }
        catch(GroupNotFound ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Group> getGroupDetailsAsync(String groupName)
    {
        return _iceI_getGroupDetailsAsync(groupName, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Group> getGroupDetailsAsync(String groupName, java.util.Map<String, String> context)
    {
        return _iceI_getGroupDetailsAsync(groupName, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupName -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Group> _iceI_getGroupDetailsAsync(String iceP_groupName, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Group> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getGroupDetails", null, sync, _iceE_getGroupDetails);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_groupName);
                 }, istr -> {
                     Group ret;
                     ret = Group.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getGroupDetails =
    {
        GroupNotFound.class
    };

    default Group[] listGroups(String userId)
    {
        return listGroups(userId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Group[] listGroups(String userId, java.util.Map<String, String> context)
    {
        return _iceI_listGroupsAsync(userId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Group[]> listGroupsAsync(String userId)
    {
        return _iceI_listGroupsAsync(userId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Group[]> listGroupsAsync(String userId, java.util.Map<String, String> context)
    {
        return _iceI_listGroupsAsync(userId, context, false);
    }

    /**
     * @hidden
     * @param iceP_userId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Group[]> _iceI_listGroupsAsync(String iceP_userId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Group[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "listGroups", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_userId);
                 }, istr -> {
                     Group[] ret;
                     ret = GroupSeqHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default void sendVoiceNoteToUser(String fromUser, String toUser, String filename, byte[] data)
        throws UserNotFound
    {
        sendVoiceNoteToUser(fromUser, toUser, filename, data, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void sendVoiceNoteToUser(String fromUser, String toUser, String filename, byte[] data, java.util.Map<String, String> context)
        throws UserNotFound
    {
        try
        {
            _iceI_sendVoiceNoteToUserAsync(fromUser, toUser, filename, data, context, true).waitForResponseOrUserEx();
        }
        catch(UserNotFound ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> sendVoiceNoteToUserAsync(String fromUser, String toUser, String filename, byte[] data)
    {
        return _iceI_sendVoiceNoteToUserAsync(fromUser, toUser, filename, data, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> sendVoiceNoteToUserAsync(String fromUser, String toUser, String filename, byte[] data, java.util.Map<String, String> context)
    {
        return _iceI_sendVoiceNoteToUserAsync(fromUser, toUser, filename, data, context, false);
    }

    /**
     * @hidden
     * @param iceP_fromUser -
     * @param iceP_toUser -
     * @param iceP_filename -
     * @param iceP_data -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sendVoiceNoteToUserAsync(String iceP_fromUser, String iceP_toUser, String iceP_filename, byte[] iceP_data, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendVoiceNoteToUser", null, sync, _iceE_sendVoiceNoteToUser);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_fromUser);
                     ostr.writeString(iceP_toUser);
                     ostr.writeString(iceP_filename);
                     ostr.writeByteSeq(iceP_data);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_sendVoiceNoteToUser =
    {
        UserNotFound.class
    };

    default void sendVoiceNoteToGroup(String fromUser, String groupName, String filename, byte[] data)
        throws GroupNotFound
    {
        sendVoiceNoteToGroup(fromUser, groupName, filename, data, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void sendVoiceNoteToGroup(String fromUser, String groupName, String filename, byte[] data, java.util.Map<String, String> context)
        throws GroupNotFound
    {
        try
        {
            _iceI_sendVoiceNoteToGroupAsync(fromUser, groupName, filename, data, context, true).waitForResponseOrUserEx();
        }
        catch(GroupNotFound ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> sendVoiceNoteToGroupAsync(String fromUser, String groupName, String filename, byte[] data)
    {
        return _iceI_sendVoiceNoteToGroupAsync(fromUser, groupName, filename, data, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> sendVoiceNoteToGroupAsync(String fromUser, String groupName, String filename, byte[] data, java.util.Map<String, String> context)
    {
        return _iceI_sendVoiceNoteToGroupAsync(fromUser, groupName, filename, data, context, false);
    }

    /**
     * @hidden
     * @param iceP_fromUser -
     * @param iceP_groupName -
     * @param iceP_filename -
     * @param iceP_data -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sendVoiceNoteToGroupAsync(String iceP_fromUser, String iceP_groupName, String iceP_filename, byte[] iceP_data, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendVoiceNoteToGroup", null, sync, _iceE_sendVoiceNoteToGroup);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_fromUser);
                     ostr.writeString(iceP_groupName);
                     ostr.writeString(iceP_filename);
                     ostr.writeByteSeq(iceP_data);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_sendVoiceNoteToGroup =
    {
        GroupNotFound.class
    };

    default Message[] getMessageHistory(String userId, String targetId, String targetType)
    {
        return getMessageHistory(userId, targetId, targetType, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Message[] getMessageHistory(String userId, String targetId, String targetType, java.util.Map<String, String> context)
    {
        return _iceI_getMessageHistoryAsync(userId, targetId, targetType, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Message[]> getMessageHistoryAsync(String userId, String targetId, String targetType)
    {
        return _iceI_getMessageHistoryAsync(userId, targetId, targetType, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Message[]> getMessageHistoryAsync(String userId, String targetId, String targetType, java.util.Map<String, String> context)
    {
        return _iceI_getMessageHistoryAsync(userId, targetId, targetType, context, false);
    }

    /**
     * @hidden
     * @param iceP_userId -
     * @param iceP_targetId -
     * @param iceP_targetType -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Message[]> _iceI_getMessageHistoryAsync(String iceP_userId, String iceP_targetId, String iceP_targetType, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Message[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getMessageHistory", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_userId);
                     ostr.writeString(iceP_targetId);
                     ostr.writeString(iceP_targetType);
                 }, istr -> {
                     Message[] ret;
                     ret = MessageSeqHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default void registerCallback(String userId, ChatCallbackPrx cb)
    {
        registerCallback(userId, cb, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void registerCallback(String userId, ChatCallbackPrx cb, java.util.Map<String, String> context)
    {
        _iceI_registerCallbackAsync(userId, cb, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> registerCallbackAsync(String userId, ChatCallbackPrx cb)
    {
        return _iceI_registerCallbackAsync(userId, cb, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> registerCallbackAsync(String userId, ChatCallbackPrx cb, java.util.Map<String, String> context)
    {
        return _iceI_registerCallbackAsync(userId, cb, context, false);
    }

    /**
     * @hidden
     * @param iceP_userId -
     * @param iceP_cb -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_registerCallbackAsync(String iceP_userId, ChatCallbackPrx iceP_cb, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "registerCallback", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_userId);
                     ostr.writeProxy(iceP_cb);
                 }, null);
        return f;
    }

    default void unregisterCallback(String userId)
    {
        unregisterCallback(userId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void unregisterCallback(String userId, java.util.Map<String, String> context)
    {
        _iceI_unregisterCallbackAsync(userId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> unregisterCallbackAsync(String userId)
    {
        return _iceI_unregisterCallbackAsync(userId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> unregisterCallbackAsync(String userId, java.util.Map<String, String> context)
    {
        return _iceI_unregisterCallbackAsync(userId, context, false);
    }

    /**
     * @hidden
     * @param iceP_userId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_unregisterCallbackAsync(String iceP_userId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "unregisterCallback", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_userId);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ChatServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ChatServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ChatServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ChatServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ChatServicePrx ice_adapterId(String newAdapterId)
    {
        return (ChatServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ChatServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ChatServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ChatServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ChatServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ChatServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (ChatServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ChatServicePrx ice_connectionCached(boolean newCache)
    {
        return (ChatServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ChatServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ChatServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ChatServicePrx ice_secure(boolean b)
    {
        return (ChatServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ChatServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ChatServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ChatServicePrx ice_preferSecure(boolean b)
    {
        return (ChatServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ChatServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ChatServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ChatServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ChatServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ChatServicePrx ice_collocationOptimized(boolean b)
    {
        return (ChatServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ChatServicePrx ice_twoway()
    {
        return (ChatServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ChatServicePrx ice_oneway()
    {
        return (ChatServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ChatServicePrx ice_batchOneway()
    {
        return (ChatServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ChatServicePrx ice_datagram()
    {
        return (ChatServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ChatServicePrx ice_batchDatagram()
    {
        return (ChatServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ChatServicePrx ice_compress(boolean co)
    {
        return (ChatServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ChatServicePrx ice_timeout(int t)
    {
        return (ChatServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ChatServicePrx ice_connectionId(String connectionId)
    {
        return (ChatServicePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ChatServicePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ChatServicePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Chat::ChatService";
    }
}
