//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

import com.zeroc.Ice.Current;

public interface ChatService extends com.zeroc.Ice.Object
{
    User login(String username, com.zeroc.Ice.Current current);

    void logout(String userId, com.zeroc.Ice.Current current);

    void sendPrivateMessage(String fromUser, String toUser, String message, com.zeroc.Ice.Current current)
        throws UserNotFound;

    void sendGroupMessage(String fromUser, String groupName, String message, com.zeroc.Ice.Current current)
        throws GroupNotFound;

    String createGroup(String groupName, String creator, com.zeroc.Ice.Current current);

    void joinGroup(String groupName, String user, com.zeroc.Ice.Current current)
        throws GroupNotFound;

    void leaveGroup(String groupName, String user, com.zeroc.Ice.Current current)
        throws GroupNotFound;

    Group getGroupDetails(String groupName, com.zeroc.Ice.Current current)
        throws GroupNotFound;

    Group[] listGroups(String userId, com.zeroc.Ice.Current current);

    void sendVoiceNoteToUser(String fromUser, String toUser, String filename, byte[] data, com.zeroc.Ice.Current current)
        throws UserNotFound;

    void sendVoiceNoteToGroup(String fromUser, String groupName, String filename, byte[] data, com.zeroc.Ice.Current current)
        throws GroupNotFound;

    Message[] getMessageHistory(String userId, String targetId, String targetType, com.zeroc.Ice.Current current);

    void registerCallback(String userId, ChatCallbackPrx cb, com.zeroc.Ice.Current current);

    void registerCallback(String userId, ChatCallback cb, Current current);

    void unregisterCallback(String userId, com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Chat::ChatService",
        "::Ice::Object"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::Chat::ChatService";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_login(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_username;
        iceP_username = istr.readString();
        inS.endReadParams();
        User ret = obj.login(iceP_username, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        User.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_logout(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_userId;
        iceP_userId = istr.readString();
        inS.endReadParams();
        obj.logout(iceP_userId, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendPrivateMessage(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        String iceP_toUser;
        String iceP_message;
        iceP_fromUser = istr.readString();
        iceP_toUser = istr.readString();
        iceP_message = istr.readString();
        inS.endReadParams();
        obj.sendPrivateMessage(iceP_fromUser, iceP_toUser, iceP_message, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendGroupMessage(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        String iceP_groupName;
        String iceP_message;
        iceP_fromUser = istr.readString();
        iceP_groupName = istr.readString();
        iceP_message = istr.readString();
        inS.endReadParams();
        obj.sendGroupMessage(iceP_fromUser, iceP_groupName, iceP_message, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_createGroup(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_groupName;
        String iceP_creator;
        iceP_groupName = istr.readString();
        iceP_creator = istr.readString();
        inS.endReadParams();
        String ret = obj.createGroup(iceP_groupName, iceP_creator, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_joinGroup(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_groupName;
        String iceP_user;
        iceP_groupName = istr.readString();
        iceP_user = istr.readString();
        inS.endReadParams();
        obj.joinGroup(iceP_groupName, iceP_user, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_leaveGroup(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_groupName;
        String iceP_user;
        iceP_groupName = istr.readString();
        iceP_user = istr.readString();
        inS.endReadParams();
        obj.leaveGroup(iceP_groupName, iceP_user, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getGroupDetails(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_groupName;
        iceP_groupName = istr.readString();
        inS.endReadParams();
        Group ret = obj.getGroupDetails(iceP_groupName, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        Group.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_listGroups(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_userId;
        iceP_userId = istr.readString();
        inS.endReadParams();
        Group[] ret = obj.listGroups(iceP_userId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        GroupSeqHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendVoiceNoteToUser(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        String iceP_toUser;
        String iceP_filename;
        byte[] iceP_data;
        iceP_fromUser = istr.readString();
        iceP_toUser = istr.readString();
        iceP_filename = istr.readString();
        iceP_data = istr.readByteSeq();
        inS.endReadParams();
        obj.sendVoiceNoteToUser(iceP_fromUser, iceP_toUser, iceP_filename, iceP_data, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendVoiceNoteToGroup(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        String iceP_groupName;
        String iceP_filename;
        byte[] iceP_data;
        iceP_fromUser = istr.readString();
        iceP_groupName = istr.readString();
        iceP_filename = istr.readString();
        iceP_data = istr.readByteSeq();
        inS.endReadParams();
        obj.sendVoiceNoteToGroup(iceP_fromUser, iceP_groupName, iceP_filename, iceP_data, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getMessageHistory(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_userId;
        String iceP_targetId;
        String iceP_targetType;
        iceP_userId = istr.readString();
        iceP_targetId = istr.readString();
        iceP_targetType = istr.readString();
        inS.endReadParams();
        Message[] ret = obj.getMessageHistory(iceP_userId, iceP_targetId, iceP_targetType, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        MessageSeqHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_registerCallback(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_userId;
        ChatCallbackPrx iceP_cb;
        iceP_userId = istr.readString();
        iceP_cb = ChatCallbackPrx.uncheckedCast(istr.readProxy());
        inS.endReadParams();
        obj.registerCallback(iceP_userId, iceP_cb, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_unregisterCallback(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_userId;
        iceP_userId = istr.readString();
        inS.endReadParams();
        obj.unregisterCallback(iceP_userId, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "createGroup",
        "getGroupDetails",
        "getMessageHistory",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "joinGroup",
        "leaveGroup",
        "listGroups",
        "login",
        "logout",
        "registerCallback",
        "sendGroupMessage",
        "sendPrivateMessage",
        "sendVoiceNoteToGroup",
        "sendVoiceNoteToUser",
        "unregisterCallback"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_createGroup(this, in, current);
            }
            case 1:
            {
                return _iceD_getGroupDetails(this, in, current);
            }
            case 2:
            {
                return _iceD_getMessageHistory(this, in, current);
            }
            case 3:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 4:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 5:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 6:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 7:
            {
                return _iceD_joinGroup(this, in, current);
            }
            case 8:
            {
                return _iceD_leaveGroup(this, in, current);
            }
            case 9:
            {
                return _iceD_listGroups(this, in, current);
            }
            case 10:
            {
                return _iceD_login(this, in, current);
            }
            case 11:
            {
                return _iceD_logout(this, in, current);
            }
            case 12:
            {
                return _iceD_registerCallback(this, in, current);
            }
            case 13:
            {
                return _iceD_sendGroupMessage(this, in, current);
            }
            case 14:
            {
                return _iceD_sendPrivateMessage(this, in, current);
            }
            case 15:
            {
                return _iceD_sendVoiceNoteToGroup(this, in, current);
            }
            case 16:
            {
                return _iceD_sendVoiceNoteToUser(this, in, current);
            }
            case 17:
            {
                return _iceD_unregisterCallback(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }

    // Si tu interfaz tiene este método:
    String[] getGroupMembers(String groupId, Current current);

    // Si tu interfaz tiene este método:
    void removeFromGroup(String groupName, String user, Current current);

    // Si tu interfaz tiene este método:
    User getUserInfo(String userId, Current current);
}
